### ISSUE TITLE
Allow vector-like objects

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/ForwardDiff.jl#107]
Currently,  `gradient` and `jacobian` only allow functions that take `Vector`s.
It would be useful to be able to use functions that take vector-like objects, e.g. those in the [`FixedSizeArrays.jl`](https://github.com/SimonDanisch/FixedSizeArrays.jl) package, or tuples.

**Comment by KristofferC** [comment]
What could be done is to remove the type constraint completely and then clearly define what methods need to be implemented for the type to be a valid input "vector" to `ForwardDiff`. This is how `IterativeSolver`` does it: https://github.com/JuliaLang/IterativeSolvers.jl#interface.
 
What happens if you just remove the type constraint on the input vector and evaluate a function with a FSA?

**Comment by mlubin** [comment]
Ref https://github.com/JuliaDiff/ForwardDiff.jl/pull/103

**Comment by KristofferC** [comment]
Problem is that `FixedSizeArray` is not a subtype of `AbstractArray`. Due to no multiple inheritance it can sometimes be impossible to do so because you need to subtype something else.

Hence, you need something like traits.

**Comment by KristofferC** [comment]
I tested this a bit by removing some type asserts and by using `eltype(x)` instead of parametrizing on `Vector{T}` everything works pretty smooth: https://gist.github.com/KristofferC/c9d72ab360b74c734491

It is actually really nice because I have some matrix -> matrix functions that I want to take the jacobian off and also some tuple -> tuple functions and they all seem to work.

**Comment by jrevels** [comment]
I believe this is fixed by #102, feel free to reopen (or tell me to reopen it) if it isn't.
