### ISSUE TITLE
ForwardDiff of in-place functions?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiff/ForwardDiff.jl#136]
Is there any way to ForwardDiff in-place functions? Most of mine look like this:

g = (du,x,t)-> du[:]=f(x,t))

for some f not in place. Is my best bet just to use f directly and then build an in-place derivative of g from the derivative of f?

**Comment by KristofferC** [comment]
http://www.juliadiff.org/ForwardDiff.jl/api.html#jacobians-of

Second section? Is that what you want?

**Comment by ChrisRackauckas** [comment]
That works in some of cases, but not for all. The best fix would be to find some way to pre-allocate `du` as a vector of the dual numbers that will be coming out of `f` (in order to use in conjunction with NLsolve). Is that possible?

**Comment by jrevels** [comment]
> That works in some of cases, but not for all.

Can you give an example where the provided `ForwardDiff.jacobian!` doesn't work? For the example you gave in the OP:

```julia
du, x, t = ... # define some values
g = (du,x,t)-> du[:]=f(x,t))

# jacobian w.r.t. to x
out = similar(du, length(du), length(x))
ForwardDiff.jacobian!(out, (du, x) -> g(du,x,t), du, x)

# jacobian w.r.t. to t
out = similar(du, length(du), length(t))
ForwardDiff.jacobian!(out, (du, t) -> g(du,x,t), du, t)
```

**Comment by ChrisRackauckas** [comment]
I can't do that inside of NLsolve.

**Comment by ChrisRackauckas** [comment]
Nevermind, I think I thought of a way to make it work.

**Comment by jrevels** [comment]
> I can't do that inside of NLsolve.

Can you provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_Working_Example) that demonstrates the limitation you ran into?

> Nevermind, I think I thought of a way to make it work.

If you wouldn't mind sharing, I'd be interested in hearing it. We might be able to use your feedback to make the package better/easier to use (or at least improve the documentation).

**Comment by ChrisRackauckas** [comment]
There is just a problem with allowing for closures. For example, in your example, what if only a function of `(x,t)` is exposed via some function? Then you would want to use the closure `(x,t)->g(du,x,t)` as the function call. But it will fail unless you can pre-allocate `du`.

**Comment by jrevels** [comment]
I'm not totally sure I understand without an example, but it kind of sounds like the problem is that you're given a non-in-place function `f(x,t)` from an external source, and you want to take it's Jacobian. If that's the case, why not just do `ForwardDiff.jacobian!(out, x -> f(x, t), x)` (or the equivalent w.r.t. to `t`)?

**Comment by ChrisRackauckas** [comment]
I can do that by modifying their source code. But that seems like a heavy-handed solution for not being able to pre-allocate a vector of duals...

**Comment by jrevels** [comment]
> I can do that by modifying their source code.

Okay, I think I'm misunderstanding your problem - in the example I'm talking about, no source code modification is needed. You are given the differentiable function `f(x,t)`. 

> not being able to pre-allocate a vector of duals...

I'm confused as to why you wish to do this when ForwardDiff is already doing this kind of work for you (or at least, it should be). If for some reason you really did want to allocate a vector of Duals, it's as easy as calling `Vector{ForwardDiff.Dual{N,T}}(n)`.

Without a code example so that I can understand the problem, I don't think I'm going to be able to help much here.

**Comment by ChrisRackauckas** [comment]
I was trying to clean up the examples, but I have to go teach. The code is here:

https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/src/ode/ode_integrators.jl#L618

You can see the Implicit Euler code can be fixed by better use of `resid` which is the only allocated vector of duals (tried and it works). This doesn't generalize very well, as you can see in the trapezoid method which uses a closure with `du1` and `du2`, but I need those instead allocated as the "right vector of duals" for that to work.

**Comment by KristofferC** [comment]
Btw, just pointing out that lines like: https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/src/ode/ode_integrators.jl#L588 will have very bad performance due to being lowered to +(a,b,c,d...) and then splatted. 

```julia
f(a) = a[1] + a[2] + a[3] + a[4] + a[5] + a[6] + a[7] + a[8]
g(a) = a[1] + a[2] + a[3] + a[4]
```

`f` is like 20 times slower here because it has too many arguments to `+`. To solve it you need to add paranthesis to group up the expressions in like 4 by 4. Ugly I know... There is an issue about it somewhere.

**Comment by jrevels** [comment]
Thanks for the link. I think my confusion came from not realizing that you were working in a situation where you were handling `Dual`s directly. 

Since this code is manually injecting dual numbers into a separate differentiable context, I just to make sure you're aware of [perturbation confusion](http://www.bcl.hamilton.ie/~barak/papers/ifl2005.pdf). In other words, the dual numbers you manually construct will mix with the dual numbers injected when NLSolve performs autodiff, possibly leading to the wrong result.

I'm still a bit confused by what this code is doing. For example, take this line:

```julia
du = map((x)->ForwardDiff.Dual{length(u),typeof(x)}(x,length(u)),zeros(u))
```

This will never work for `length(u) != 1`, since you're not passing in the same number of perturbations specified by the type parameter. Even if it did work, it would still fail for `length(u) > 10`, since the `Dual` type is limited to `10` simultaneous perturbations for performance reasons (i.e. more than that can cause thrashing). I also don't understand why the dual number's perturbation should be seeded with the length of the input vector...

What is the motivation for injecting dual numbers manually before passing the function to NLSolve? AFAICT, `du` is never used after the initial differentiation, so the only effect of making `du`'s elements dual numbers is to induce perturbation confusion in NLSolve's autodiff code.

**Comment by ChrisRackauckas** [comment]
>f is like 20 times slower here because it has too many arguments to +. To solve it you need to add paranthesis to group up the expressions in like 4 by 4. Ugly I know... There is an issue about it somewhere. 

Thanks for pointing that out. I'll go find the issue. I assumed the compiler would turn those into a bunch of FMA's. Maybe it's best just to loop over the appropriate indices tmp[:]+=b[i]*k[i], that would let the compiler optimize it, right? That's a different story though.

> Since this code is manually injecting dual numbers into a separate differentiable context, I just to make sure you're aware of perturbation confusion. In other words, the dual numbers you manually construct will mix with the dual numbers injected when NLSolve performs autodiff, possibly leading to the wrong result.

I'm not making Dual numbers that mean anything... just trying to make `du` a pre-allocated vector of Duals so that it doesn't make the vector each time. Obviously using `du[:] = f(u,t)` works, but I just want to do `f(du,u,t)` for better performance... and all that it requires is for `du` to be an appropriately typed array. 

And obviously the code that doesn't work doesn't work, I said to look at `du1` and `du2` of the trapezoidal method. The Euler method only needs one temporary around, so it will work without the full closure. The new master has the Euler method fully in-place using the 1 temporary that's given, `resid`. The trapezoidal rule can't do that, so unless there's a way to properly pre-allocate an array of Duals and push it in via the closure, it's not going to work (without having a temporary).

**Comment by KristofferC** [comment]
Dual vectors are cached inside ForwardDiff for a given length and element type. 

Why are you not just passing `du` in? You are differentiating with respect to u, right?

**Comment by ChrisRackauckas** [comment]
`du` is just a bad name for it. It's just a variable to hold the temporary allocation. 

Let's start over. Any problem where you'd want to differentiate and have to use a closure to avoid allocations has this problem. Another example:

```julia
function f(output,u,t,tmp1,tmp2)
  for i in eachindex(u)
    tmp1[i] = u[i]*t # in-place changes tmp1
    tmp2[i] = exp(tmp1[i]^2 * t^2) # in-place changes tmp2
    output[i] = sin(tmp2[i] + erf(tmp[1])) # Needs tmp1 and 2
   end
```

is an in-place function which calculates something and puts the result in `output`. I makes no allocations. I want to use ForwardDiff on `(output,u,t) -> f(output,u,t,tmp1,tmp2)` which is just a closure of pre-allocated vectors to get rid of temporary allocations. The problem is, what do I type tmp1 and 2?

**Comment by KristofferC** [comment]
Thanks, that was a good example. I have done similar things like that.  Something like this:

````jl
import ForwardDiff.Dual

immutable DiffCache{T, S}
	du::Vector{T}
	dual_du::Vector{S}
end

function DiffCache{chunk_size}(T, length, ::Type{Val{chunk_size}})
    DiffCache(zeros(T, length), zeros(Dual{chunk_size, T}, length))
end

get_du(dc::DiffCache, T::Dual) = dc.dual_du
get_du(dc::DiffCache, T) = dc.du

const CHUNK_SIZE = 10
const CACHE = DiffCache(Float64, 20, Val{CHUNK_SIZE})

function f(output, u, cache)
  du = get_du(cache, eltype(u))
  for i in eachindex(u)
    du[i] = u[i]
   end
   return du
end
````

**Comment by ChrisRackauckas** [comment]
Oh I see, so it needs a dual and a non-dual pre-allocated for each cache vector? I'll give that a try.

**Comment by ChrisRackauckas** [comment]
What exactly dues the chunk_size parameter do?

**Comment by KristofferC** [comment]
Decides how many directional derivatives to take per function call. It is just an optmization.

**Comment by ChrisRackauckas** [comment]
+1 That seemed to have worked. However, I had to change the following:

```julia
get_du{T<:Dual}(dc::DiffCache, ::Type{T}) = dc.dual_du
```

to get that to dispatch correctly. More importantly and the one I have a question about is that I also had to change `CHUNK_SIZE=8`. It seems by default ForwardDiff was generating Duals with 8 directional derivatives per call. Is there any way to know this in advance? Does this change per equation, per install, per some default in ForwardDiff?

**Comment by KristofferC** [comment]
It does a heuristic. You can set it explicitly as well.

**Comment by ChrisRackauckas** [comment]
I just gave it a read through. It says it does a heuristic based on input dimension, but it doesn't say what it is. Which function does the heuristic calculation in ForwardDiff? This way the chunk size would correctly be the same as ForwardDiff. The other alternative would be to have NLsolve expose the chunk parameter. But it would be nice to just plug into the same heuristic.

**Comment by KristofferC** [comment]
https://github.com/JuliaDiff/ForwardDiff.jl/blob/2f712dc1da9c801b537c31ea5cc3400987043124/src/ForwardDiff.jl#L54

**Comment by ChrisRackauckas** [comment]
Thanks. Just for future reference, I made a function 

```julia
DiffCache(u::AbstractArray) = DiffCache(eltype(u),length(u),Val{ForwardDiff.pickchunksize(u)})
```

and so now making the cache is just `cache1=DiffCache(u)`, and using the cache is as above. Tests pass! Thanks for the help. I'll ask about the long additions thing somewhere else (Gitter?), I can't find the issue.

**Comment by jdebecdelievre** [comment]
Hello,

I'm reviving this issue because I need a similar feature.
If I am right, the use of a DiffCache{T,S} in the fix proposed above requires to know the Dual type (and hence the Tag type)  at allocation time, which we don't know yet. Things happen in the following order:
```
function f(u, cache)
...
return output
end
cache = DiffCache(...*requires Dual type*...)
f_(output,u) = f(output, u, cache)
cfg = JacobianConfig(f_, u) # moment where Tag type is actually created
J = jacobian(f_, u, cfg)
```

I think that a clean fix would be to let the user provide its cache (as a tuple of arrays for instance) to JacobianConfig:
```
function JacobianConfig(f::F,
                        x::AbstractArray{V},
			cache::NTuple{Nt,AbstractArray{V}} where Nt,
                        ::Chunk{N} = Chunk(x),
                        ::T = Tag(f, V)) where {F,V,N,T}
    seeds = construct_seeds(Partials{N,V})
    duals = similar(x, Dual{T,V,N})
    cache_duals = (similar(c, Dual{T,V,N}) for m in cache) # added line
    return JacobianConfig{T,V,N,typeof(duals)}(seeds, duals, cache_duals)
end
```
(would require adding the relevant field to the JacobianConfig structure).
The `vector_mode_dual_eval!` function would become:
```
function vector_mode_dual_eval!(f::F, cfg::Union{JacobianConfig,GradientConfig}, x) where {F}
    xdual = cfg.duals
    seed!(xdual, x, cfg.seeds)
    return f(xdual, cfg.cache_duals)
end
```

Let me know if I am getting something wrong. Happy to work towards a pull request if you think that such a change would be of interest.

Best
Jean

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/PreallocationTools.jl does all of that via reinterpret and such.

**Comment by jdebecdelievre** [comment]
Thank you for pointing the package out! This works for me right now.

Is there a reason for not supporting the feature directly in ForwardDiff? 
Since `AbstractConfig` types have a field `duals` which can be a tuple `(xduals, yduals)`, it feels like it could naturally be extended to `(yduals, xduals, cacheduals)`.

**Comment by ChrisRackauckas** [comment]
That wouldn't work. The caching needs to occur on the user-defined caches, not in the config.
