### ISSUE TITLE
Why does `Dual` inherit from `Real` but not `Number`?

### ISSUE THREAD

**Issue by xukai92** [JuliaDiff/ForwardDiff.jl#156]
I thinks the definition should be `Dual{N,T<:Real} <: Number`.

**Comment by jrevels** [comment]
There was [a long discussion about this in a previous issue](https://github.com/JuliaDiff/ForwardDiff.jl/issues/66). It's tempting to think that `Dual <: Number` in order to mirror the dual number set's mathematical relationship to the set of reals, but the Julia type hierarchy needn't reflect the relationship between these sets. We ultimately decided it would be most practical for `Dual <: Real` because `Dual` should programmatically support all `Real` operations, and be insertable wherever a `Real` is allowed.

**Comment by xukai92** [comment]
Actually I came up with this issue when I was trying to use `Dual` with `Distributions.jl` package, where they import functions from `Rmath.jl`, which replies on external R library. As these functions supports floats and ints, so the define the type with `Real` in their wrapper. This lead to the fact that I can pass them to the wrapper but it will give error.

**Comment by jrevels** [comment]
Yeah, unfortunately ForwardDiff's `Dual` cannot be used where generic `Real` types are not allowed (such as in calls to external libraries). It's an inherent limitation of language-specific AD - the code that's getting differentiated has to be Julia code "all the way down."
