### ISSUE TITLE
InexactError()

### ISSUE THREAD

**Issue by genwei007** [JuliaDiff/ForwardDiff.jl#17]
Hi Scidom,
I have the following model:
~~~~~~~~~~~~~~~~~~~~~~~~
point = 2 # can be used within function
y = [0:(point - 1)]
function GPCM(para)
  a = para[1]
  d = para[2]
  tau = para[3:4]
  t = para[5]
  nu = zeros(point)
  for k = 1:point
    nu[k] = exp(a.*(y[k].*(t-d) - sum(tau[1:k]) )) [1]
  end
  de =  sum(nu)
  p = nu ./ de
end

para = [1.,0.,0.,0.,1.]
Jac = forwarddiff_jacobian(GPCM, Float64, fadtype=:typed)
Jac(para)
~~~~~~~~~~~~~~~~~~~~~~~
But, it returns an error message:
    InexactError()
    in setindex! at array.jl:307

It indicates that the nu[k] is not right. Hessian cannot be obtained as well. Any suggestion about this? 
Thanks.

**Comment by scidom** [comment]
This is issue has been resolved after doing what @mlubin suggested. Sorry that it took months before I sat down to check it out. The problem was exactly that the routines of ForwardDiff don't work with generic input times, so when you defined `zeros` you have to explicitly tell what type of elements the resulting `nu` vector will hold. I will close this issue now. For the sake of completeness, here is the operational code for your example in Julia 0.4:

```
using ForwardDiff

point = 2 # can be used within function
y = [0:(point - 1);]
function GPCM(para)
  a = para[1]
  d = para[2]
  tau = para[3:4]
  t = para[5]
  nu = zeros(eltype(para), point)
  for k = 1:point
    nu[k] = exp(a.*(y[k].*(t-d) - sum(tau[1:k]) )) [1]
  end
  de =  sum(nu)
  p = nu ./ de
end

para = [1.,0.,0.,0.,1.]
Jac = forwarddiff_jacobian(GPCM, Float64, fadtype=:typed)
Jac(para)
```

**Comment by genwei007** [comment]
Hi scidom,

How about 'forwarddiff_hessian' which is not applicable in the present case... Still got errors. Thanks.

**Comment by scidom** [comment]
Hi @genwei007, let me check this and will let you now if there is an obvious fix.
