### ISSUE TITLE
Bug in `typed_fad_gradient`

### ISSUE THREAD

**Issue by gragusa** [JuliaDiff/ForwardDiff.jl#24]
Consider the following function 

```
using ForwardDiff;
srand(1)
y = randn(100);
x = randn(100,2);
g(theta)  = x.*(y-x*theta);
gn(theta) = vec(sum(g(theta), 1));
gn([.1,.1])
```

I want to use `typed_fad_gradient` to calculate the derivative of `gn` with respect to `theta`. This code 

```
    h1 = ForwardDiff.typed_fad_gradient(gn, Float64);
    h1([.1,.1])
```
provides the correct gradient
``` 
 2x2 Array{Float64,2}:
  -103.869     11.1779
    11.1779  -119.393
```
as it can be seen by comparing it with the analytic gradient
```
    -x'x
```
	
Suppose now the function to be derived is defined using a linear algebra
operation, i.e.,

```
 p = ones(100);
 wgn(theta) = g(theta)'p;
 h2 = ForwardDiff.typed_fad_gradient(wgn, Float64);
 h2([.1,.1])
```
Although `wgn([.1,.1]).==gn([.1,.1])`, the gradient returned by `type_fad_gradient` is
```
 2x2 Array{Float64,2}:
  103.869   -11.1779
  -11.1779  119.393  
```
which is different from `h1([.1,.1])` and from `-x'x` by a factor of `-1`.

**Comment by scidom** [comment]
@gragusa not a 100% what is going on here, but the most likely problem is that ForwardDiff is meant to work with a predefined set of arithmetics operations, so the linear algebra operation is not anticicpated to work without defining it first generically.

**Comment by scidom** [comment]
Actually, I am 100% that the problem is exactly this, you can exploit ordinary multiplication because it is defined in the packages codebase, whereas algebraic operations such the one you tried to used are not available. I will close this issue now. If you want to submit a PR to define transposition or any other algebraic operation, feel free to do so, I will review your PR.
