### ISSUE TITLE
silent error for function that doesn't propagate Dual

### ISSUE THREAD

**Issue by goretkin** [JuliaDiff/ForwardDiff.jl#241]
```julia
using ForwardDiff
bad(x) = x.value

julia> ForwardDiff.derivative(bad, 0.5)
0.0
```
I would prefer an explicit error if the function is not compatible with forward-mode differentiation. Can ForwardDiff check that the output of the "differand"/"derivand" contains a dual part?

I came across this when using [Colors.jl](https://github.com/JuliaGraphics/Colors.jl).

```julia
using Colors
using ForwardDiff

f(x) = colordiff(RGB(0.0, 0.0, x), RGB(0.0, 0.0, 0.0))
@show ForwardDiff.derivative(f, 0.5)
@show Calculus.derivative(f, 0.5)
Pkg.status("Colors"), Pkg.status("ForwardDiff");
```

produces

```
ForwardDiff.derivative(f, 0.5) = 0.0
Calculus.derivative(f, 0.5) = 20.908844662039417
 - Colors                        0.7.3
 - ForwardDiff                   0.4.2
```

because
```julia
julia> RGB(0.0, 0.0, ForwardDiff.Dual(0.5, 1.0))
RGB{N0f8}(0.0,0.0,0.502)
```

**Comment by KristofferC** [comment]
This feels impossible to detect.

**Comment by goretkin** [comment]
@kristofferc, could you explain?

**Comment by KristofferC** [comment]
For AD with dual numbers to work the duals need to propagate through all operations. If some `con ert` function (or something like using `.value`) strips the partials the output will to ForwardDiff.jl just look like a function `f(x) = c` which has zero derivative.

**Comment by jrevels** [comment]
ForwardDiff can only differentiate code that is "numerically type generic", i.e. [type generic up to `Real`](http://www.juliadiff.org/ForwardDiff.jl/stable/user/limitations.html). Code which directly modifies fields of arbitrarily typed input (like `bad`) isn't numerically type generic at all, and is thus impossible for ForwardDiff to support. 

Note that functions like `bad` are (as the name would imply) quite bad regardless of AD; code performing direct field accesses should almost always be type-quantified. Otherwise, the code is vulnerable to unintended consequences like we see here.

**Comment by goretkin** [comment]
@KristofferC, it doesn't look "just like a [type-stable] function which has zero derivative".

@jrevels I'm looking for clarification. I understand that ForwardDiff cannot differentiate a function like `bad`, and I'm not saying that it should. But can ForwardDiff provide an error message? I would like, for example, for there to be even a no-method error when trying to extract the dual part of a number that has no dual part. I understand this would be a departure from the current behavior of, e.g. `imag(1)` or `dual(1)`, both of which return 0.

`bad` was just a simple example of code that I expect to error out, and for the issue I'm bringing up, I don't think it is relevant to focus on its implementation, or that it would be bad to write code like that. If ForwardDiff is given a bad function, I think it can report an error, as opposed to reporting an incorrect derivative.

What about `f`, which relies on some other library that perhaps is not written in the most type-generic way? I don't see why ForwardDiff cannot provide an error message here.

I imagine it would be possible to define `strict_dual`, that is only defined on types that have an explicit dual part. If a function throws away the dual part, trying to extract the dual part from its return value would result in an error.

**Comment by jrevels** [comment]
> If ForwardDiff is given a bad function, I think it can report an error, as opposed to reporting an incorrect derivative.

I agree that it's more desirable to error loudly than silently. Definitely open a PR if you have a correct/performant implementation for catching "bad functions" in more cases than ForwardDiff can currently handle!

> bad was just a simple example of code that I expect to error out, and for the issue I'm bringing up, I don't think it is relevant to focus on its implementation, or that it would be bad to write code like that. 

Okay, can you give a more representative MRE of what you're talking about? From your original example, I had thought this issue was about catching errors from type-unquantified field accesses (which I'm pretty sure is impossible to accomplish correctly/performantly, even if Julia had `getfield` overloading). 

> I understand this would be a departure from the current behavior of, e.g. imag(1) or dual(1), both of which return 0.

ForwardDiff doesn't define either of these functions, though I think I get what you mean. ForwardDiff defines `partials`, which has the following behavior:

```julia
julia> ForwardDiff.partials(1.0)
0-element ForwardDiff.Partials{0,Int64}

julia> ForwardDiff.partials(1.0, 1)
0.0
```

Treating `T<:Real && !(T<:Dual)` as `Dual{_,T,N}` with all zero derivative coefficients is correct for the class of functions ForwardDiff supports, and there exist conversion/promotion methods that utilize this fact. 

Are you saying that ForwardDiff should throw an error on `ForwardDiff.derivative(x -> 1, 1)`?

**Comment by goretkin** [comment]
>  I had thought this issue was about catching errors from type-unquantified field accesses

Ah, I see. Right, so I think it should be possible to define `bad`, and to call it. (No error here). Just that `ForwardDiff.derivative(bad, 1)` would error when the package went to extract the partials.

(Also, I don't understand exactly what a type-quantified field access is, and how making sure field accesses are type-quantified would prevent a function like `bad` from producing the result that I think is undesirable.)

> Are you saying that ForwardDiff should throw an error on ForwardDiff.derivative(x -> 1, 1)?

I hadn't considered it, but indeed in this view, `ForwardDiff.derivative(x -> 1, 1)` would also produce an error. I understand this might be too breaking and therefore not within the realm of consideration, but personally I don't mind an error when trying to differentiate a function like `x-> 1`. That function can be re-written in a type-generic way, so that it returns a `one(typeof(x))`. The benefit of the error checking would, for me, outweigh the convenience of taking the derivative of `x->1`.

> Okay, can you give a more representative MRE of what you're talking about? 
Sorry it's not so minimal, but did you take a look at the example with `colordiff`? What can I, as a user, do to find out if my function `f` is compatible with ForwardDiff, without needing to look at the implementation for all the subfunctions within `x`? If there's something I can do (which I believe just boils down to detecting that the function does not propagate dual numbers), then I think that `ForwardDiff` could do it too.

**Comment by goretkin** [comment]
It turns out the issue within `Colors.jl` is a the use of a `round` call (https://github.com/JuliaMath/FixedPointNumbers.jl/blob/65d1b00e02d2a1211ee8ffca2232db77e7c696fe/src/normed.jl#L39), which in the ForwardDiff, is implemented such that it doesn't propagate Dual parts (not that it makes a difference here in terms of calculating an answer to the derivative, since any derivative through round will return zero.).

I think I'm starting to understand the picture that "no dual part <-> zero derivative", which is why 
`round(Dual(x, 1)) == x`
instead of 
`round(Dual(x, 1)) == Dual(x, 0)`.

it turns out that the original `f` *is* "compatible" with taking forward derivatives, it's that the function is piecewise constant (due to the `round`), and so ForwardDiff correctly returns 0.

Case closed, as far as I can tell.
