### ISSUE TITLE
error in documentation on retrieving multiple results

### ISSUE THREAD

**Issue by carlosbrody** [JuliaDiff/ForwardDiff.jl#273]
I am using ForwardDiff v0.6, and noticed that the description in the documentation as to how to retrieve multiple results for ForwardDiff v0.6 appears to be wrong: following what the documentation says produces an error. 

If I follow instead what the documentation says for v0.7, then things work fine.

>  Pkg.installed("ForwardDiff")

v"0.6.0"

>  f = x -> sum(x)^2;   x = [1.1, 2.2]

> using DiffBase
> out = DiffBase.HessianResult(x)
> out = ForwardDiff.hessian!(out, f, x) # re-alias output!

ERROR: MethodError: no method matching hessian!  [...]

**In contrast, following the doc for v0.7, which is not the one I am using:**

> using DiffResults
> out = DiffResults.HessianResult(x)
> out = ForwardDiff.hessian!(out, f, x)

MutableDiffResult(10.890000000000002, ([6.6, 6.6], [2.0 2.0; 2.0 2.0]))

(p.s. **THANKS** for writing ForwardDiff!  I am a very happy user)

**Comment by jrevels** [comment]
Ah, I fixed this typo a while ago but the fix is only in the [latest docs](http://www.juliadiff.org/ForwardDiff.jl/latest/user/upgrade.html#Retrieving-Lower-Order-Results-1), not the stable docs. Sorry about that!

I've backported the typo fix so it should now appear in the current version of the docs.

> (p.s. THANKS for writing ForwardDiff! I am a very happy user)

❤️
