### ISSUE TITLE
Pre-recording a gradient tape

### ISSUE THREAD

**Issue by ngiann** [JuliaDiff/ForwardDiff.jl#350]
I am using ForwardDiff to great success, but I have been wondering whether I could speed up the calculation of gradients.

In ReverseDiff  one can pre-record a gradient tape, which speeds up calculations like follows (bit below taken from an example):

```
# pre-record a GradientTape for `f` using inputs of shape 100x100 with Float64 elements
const f_tape = GradientTape(f, (rand(100, 100), rand(100, 100)))

# compile `f_tape` into a more optimized representation
const compiled_f_tape = compile(f_tape)

# this should be the fastest method, and non-allocating
gradient!(results, compiled_f_tape, inputs)
```

Is there something equivalent for ForwardDiff? I have been browsing the documentation but it's not obvious to me whether this is possible.

Many thanks.

**Comment by jrevels** [comment]
ForwardDiff doesn't require or use a tape, since the application of the chain rule follows the normal execution order of the program being differentiated.

I guess the closest "equivalent" would be to preallocate the memory ForwardDiff requires for storing seeds/`Dual` numbers: http://www.juliadiff.org/ForwardDiff.jl/latest/user/api.html#Preallocating/Configuring-Work-Buffers-1.

**Comment by ngiann** [comment]
thanks
