### ISSUE TITLE
Performance in High Dimensions

### ISSUE THREAD

**Issue by dtjohnson** [JuliaDiff/ForwardDiff.jl#358]
This library is fantastic, and I've had great success in low dimensions. However, I've run into some performance issues in a problem with a large number of dimensions (~160). The gradient calculation is much slower than the equivalent Python with [Autograd](https://github.com/HIPS/autograd). So I put together a couple notebooks explaining the issue with a toy problem: [Grad Benchmarks.zip](https://github.com/JuliaDiff/ForwardDiff.jl/files/2397430/Grad.Benchmarks.zip)

Here's the toy objective function:
```julia
function objective(a)
    y = exp.(a*10)
    return sum((y-y_obs).^2)
end
```

I'm calculating the gradient with:
```julia
gcfg = ForwardDiff.GradientConfig(objective, start)
grad! = (res,x) -> ForwardDiff.gradient!(res, objective, x, gcfg)
g = zeros(n)
@benchmark grad!(g, start)
```

As the docs recommend, I've tried setting the chunk size, but it only seems to make it worse. Here are plots of the execution time vs. the equivalent Python for both the objective function and the gradient.
![image](https://user-images.githubusercontent.com/218771/45759555-28767180-bbf6-11e8-91db-56b821d8f269.png)
![image](https://user-images.githubusercontent.com/218771/45759580-362bf700-bbf6-11e8-9c3f-6a27015dd5b9.png)

You can see that Python is much slower for the objective function in low dimensions but catches up in high dimensions as most of the work is done in numpy. For the gradient, Autograd is much slower than ForwardDiff in low dimensions, but then Forward diff blows up at around 100 dimensions.

Am I missing something obvious to improve performance?

**Comment by KristofferC** [comment]
> Am I missing something obvious to improve performance?

You are comparing two different algorithms with different scaling behavior with each other (forward mode AD vs reverse mode AD).

**Comment by jrevels** [comment]
> Am I missing something obvious to improve performance?

Nope, good perf analysis though! As @KristofferC mentioned, this is just the expected scaling behavior of forward-mode AD; forward-mode AD is very useful for low-dimensional functions, or functions where the number of internal primitive operations grows drastically faster than the number of inputs, or operations in which the output has a dimension equal to or greater than the input. 

I wrote a short section on this a while ago, if it's helpful: https://github.com/JuliaDiff/ReverseDiff.jl#should-i-use-reversediff-or-forwarddiff

For example, if your target function was written with loops + scalar operations instead of vectorized operations, then Julia + ForwardDiff would beat Python + autograd at higher dimensions than in your original benchmark (since scalar ops are slow in Python, and have a high cost-to-compute ratio for reverse-mode in general). Eventually, reverse-mode's scaling would still win out, however. That's my guess, anyway, it'd be worth the experiment.

Gonna close this, but feel free to keep discussing.

**Comment by dtjohnson** [comment]
Ah! Thanks. I had assumed Autograd was forward-mode as well. I now see it is reverse-mode. Thanks for the clarification!

**Comment by dtjohnson** [comment]
To completely close this out, I ran the same example with ReverseDiff. As you pointed out, ForwardDiff is much better in low dimensions and ReverseDiff in high. Here's a plot:
![image](https://user-images.githubusercontent.com/218771/45770448-697b7f80-bc10-11e8-912a-4f558bed4a37.png)

And on a log-scale:
![image](https://user-images.githubusercontent.com/218771/45770482-7dbf7c80-bc10-11e8-8b04-06fd71612ae6.png)
