### ISSUE TITLE
Sparse Hessian

### ISSUE THREAD

**Issue by raphaelchinchilla** [JuliaDiff/ForwardDiff.jl#458]
Hi all,

I am trying to use ForwardDiff in an optimization problem. I have to compute a hessian that I know is sparse (very sparse even). Is there a way to force ForwardDiff to return a sparse array? If yes, would that work with DiffResults? (but only for a sparse Hessian, no sparse gradient)

**Comment by ChrisRackauckas** [comment]
ForwardDiff.jl doesn't directly support sparse. SparseDiffTools.jl extends ForwardDiff.jl with sparse differentiation. Right now it doesn't have Hessian coloring though.

**Comment by raphaelchinchilla** [comment]
Thanks @ChrisRackauckas 

Would it work to use jacobian coloring on the gradient (obtained with ForwardDiff or ReverseDiff) to obtain a hessian coloring?

**Comment by ChrisRackauckas** [comment]
No, since it needs a different coloring. One thing you might be able to do is make use of Hessian-vector products, which are Hessian-free calculations of `H*v` and that's provided in the library, but direct sparse Hessian calculations need a little bit more (star coloring and Hessian decomposition).
