### ISSUE TITLE
Incorrect behavior of max(d::Dual, ::Float64) when partials are -Inf

### ISSUE THREAD

**Issue by jeffreyesun** [JuliaDiff/ForwardDiff.jl#603]
See the following MWE:
```
using ForwardDiff
a = ForwardDiff.Dual(-1.0, -Inf)
a = max(a, 0.0) #Dual{Nothing}(0.0,NaN)
```
The correct output should be `Dual{Nothing}(0.0,0.0)`, as the constant 0.0 does not depend on the x. This was causing my code to fail as the solver I was using couldn't handle the NaN values.

**Comment by devmotion** [comment]
Did you try to enable NaN-safe mode? https://juliadiff.org/ForwardDiff.jl/dev/user/advanced/#Fixing-NaN/Inf-Issues

**Comment by jeffreyesun** [comment]
I tried it, but the problem persists. I should note that the derivative in this case is not undefined; it should be equal to exactly zero.

**Comment by jeffreyesun** [comment]
The code being called appears to be `define_binary_dual_op` in `src/dual.jl`, but I can't make heads or tails of it.

**Comment by mcabbott** [comment]
It's knotty but I think it ends up here:
https://github.com/JuliaDiff/DiffRules.jl/blob/489e2942e10776c96ab70c5044f595951bbbcaab/src/rules.jl#L93

I don't think there's any reason those should be `one(x)` not just `true`/`false`, and since `false` is a strong zero, I believe it would fix the problem.

This is what ChainRules has, BTW:

https://github.com/JuliaDiff/ChainRules.jl/blob/5818173b31fac9d358acda21f5751978a5dcb2e5/src/rulesets/Base/fastmath_able.jl#L220

**Comment by devmotion** [comment]
I opened a PR: https://github.com/JuliaDiff/DiffRules.jl/pull/87
